### ISSUE TITLE
Conflict with VS Code SCM panel

### ISSUE THREAD

**Issue by JohnCido** [cssho/vscode-svgviewer#35]
After installing the extension, I find that SCM panel shows a message: No available SCM.

- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

**Comment by cssho** [comment]
@JohnCido 
Thank you for reporting.
I unthinkable that. I can't reproducible .
Any error messages in Developer Tools ?

**Comment by JohnCido** [comment]
![svg viewer conflict](https://user-images.githubusercontent.com/7105485/30793974-1e22910e-a18b-11e7-9fd7-b7c3d2fcd42b.gif)
Confirmed that after enabled SVG Viewer and open SCM panel. There's no output in developer tool console.

Issue in official repo: https://github.com/Microsoft/vscode/issues/34879
