### ISSUE TITLE
Option to set the background to white

### ISSUE THREAD

**Issue by clankill3r** [cssho/vscode-svgviewer#38]
I would really prefer a white background over the checker pattern.
For the rest great extension!

**Comment by cssho** [comment]
@clankill3r 
Sorry for replying so late.
Override SVGViewer settings to this:
```
"svgviewer.transparencycolor": "white"
```

transparencycolor:null
![image](https://user-images.githubusercontent.com/9441609/35925945-5a81b3e2-0c6a-11e8-944d-67991ff7a8f3.png)

transparencycolor:white
![image](https://user-images.githubusercontent.com/9441609/35926024-878088c8-0c6a-11e8-87b7-6fa463f96511.png)
