### ISSUE TITLE
Support for external CSS missing

### ISSUE THREAD

**Issue by SuperOok** [cssho/vscode-svgviewer#41]
The viewer seems to not support external CSS specified in an xml-stylesheet directive:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="mystyles.css" type="text/css"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="200" version="1.1" width="200">
...
</svg>
```

**Comment by SuperOok** [comment]
I guess the problem is that the svgProvider.ts [1] an html-embedded svg is created and the svg-snippet is embedded there. However, in html a CSS file is referenced differently to an XML document which pure SVG is.

[1] https://github.com/cssho/vscode-svgviewer/blob/master/src/svgProvider.ts

**Comment by cssho** [comment]
@SuperOok 
I'm so late. Added support for external CSS in the latest version.
