### ISSUE TITLE
Bug: show Button when view extensions

### ISSUE THREAD

**Issue by dacapoday** [cssho/vscode-svgviewer#42]
When I browse extensions(such as XML Tools) page, svgviewer show its button on the top bar.
Click the button nothing happens.
Will only happen on some extensions page, and only test on vscode 1.23.0 windows.
![screen_shot](https://i.loli.net/2018/05/06/5aee819897f97.png)

**Comment by cssho** [comment]
Fix at [v1.4.4](https://github.com/cssho/vscode-svgviewer/releases/tag/1.4.4) .
