### ISSUE TITLE
Allow zooming of SVG with mouse wheel

### ISSUE THREAD

**Issue by totkeks** [cssho/vscode-svgviewer#43]
I just installed this extension, because vscode unfortunately can't display SVG out of the box. But then I wanted to zoom into some smaller SVG icons and noticed, that this doesn't work with the mouse wheel.

When using ctrl+ or ctrl- it zoomed the whole application windows, which was not what I wanted.

Could you please add the option to zoom the SVG preview? Either with mouse wheel or with buttons.

**Comment by cssho** [comment]
@totkeks 
Added support for zooming of SVG in the latest version. 
You can use it by holding ctrl/cmd and using mouse wheel.

**Comment by totkeks** [comment]
Smooth. Works great. Thank you! :-)
