### ISSUE TITLE
SVG preview shows contents of any edited file

### ISSUE THREAD

**Issue by joaomoreno** [cssho/vscode-svgviewer#5]
1. Open an SVG file
2. Open the preview on the side
3. Open any other file
4. Make a change to that file

Notice how the preview (`/svg-preview`) now show the contents of that file instead of the svg.

![image](https://cloud.githubusercontent.com/assets/22350/14276428/27c81a08-fb1f-11e5-8e2a-bd09710b9d27.png)

**Comment by joaomoreno** [comment]
[Maybe we should filter on `*.svg` only](https://github.com/cssho/vscode-svgviewer/blob/master/src/extension.ts#L69)?

**Comment by cssho** [comment]
Thank you for reporting.
